---

- name: Create mail storage
  file:
    path:  '{{ item.path }}'
    state: directory
    owner: '{{ item.user | default( dovecot_user ) }}'
    group: '{{ item.group | default( dovecot_group ) }}'
    mode:  '{{ item.mode | default( "0770" ) }}'
  with_items:
  - { path: '{{ dovecot_dir_storage }}', group: 'mail' }
  - { path: '{{ dovecot_dir_storage }}/tmp' }
  - { path: '{{ dovecot_dir_storage }}/home', group: 'mail' }
  - { path: '{{ dovecot_dir_storage }}/indexes' }

- name: Create log dir, if defined
  file:
    path: "{{ dovecot_log_dir }}"
    state: directory
    recurse: yes
  when: dovecot_log_dir is defined and dovecot_log_dir
